#!/usr/bin/env bash

if [[ -s "/home/action/.rvm/environments/ruby-1.9.3-p374@global" ]]
then
  source "/home/action/.rvm/environments/ruby-1.9.3-p374@global"
  exec irb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.rvm/environments/ruby-1.9.3-p374@global'" >&2
  exit 1
fi
