#!/usr/bin/env bash

if [[ -s "/home/action/.rvm/environments/ruby-2.0.0-p0@railsapps-learning-rails" ]]
then
  source "/home/action/.rvm/environments/ruby-2.0.0-p0@railsapps-learning-rails"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.rvm/environments/ruby-2.0.0-p0@railsapps-learning-rails'" >&2
  exit 1
fi
