#!/usr/bin/env bash

if [[ -s "/home/action/.rvm/environments/ruby-1.9.3-p374" ]]
then
  source "/home/action/.rvm/environments/ruby-1.9.3-p374"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.rvm/environments/ruby-1.9.3-p374'" >&2
  exit 1
fi
